apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- prometheus-pvc.yml
- prometheus-deployment.yml
- prometheus-service.yml
- prometheus-ingress.yml
- prometheus-serviceaccount.yml
- prometheus-clusterrole.yml
- prometheus-clusterrolebinding.yml
- node-exporter-daemonset.yml

configMapGenerator:
- name: prometheus-config
  files:
  - "prometheus.yml"